import { data, rating, safe, slug, trackId } from "./music/data.js";
import { radar, waveform } from "./rating/visuals.js";
import { link } from "./layout/shell.js";

export const home = () => {
  const featuredTrack = data.songs.entries.find((track) => track.title === "向日葵朝着夜") || data.songs.entries[0];
  const featuredAlbum = data.profile.albumArchive.find((album) => album.title === "Sweetener") || data.profile.albumArchive[0];
  const current = data.songs.entries.filter((track) => track.scores?.overall !== null && track.scores?.overall !== undefined).slice(0, 4);
  const draft = [{ title: "01", overall: 7.6 }, { title: "02", overall: 8.4 }, { title: "03", overall: 7.9 }, { title: "04", overall: 9.1 }, { title: "05", overall: 8.6 }, { title: "06", overall: 8.2 }];
  return `<section class="home-hero"><span class="eyebrow mono">PERSONAL ARCHIVE / ISSUE 001</span><h1>How I<br><em>hear music.</em></h1><p>Melody opens the door.<br>Everything else has to earn its place.</p>${link("/taste/philosophy", "READ THE METHOD ↓", "text-link")}</section><section class="home-section"><span class="eyebrow mono">CURRENTLY LISTENING</span><div class="current-grid">${current.map((track) => `<article><p>${safe(track.artist)}</p><h2>${safe(track.title)}</h2><strong>${rating(track.scores.overall)}</strong>${link(`/archive/tracks/${trackId(track)}`, "Open", "card-link")}</article>`).join("")}</div></section><section class="feature-split"><article><span class="eyebrow mono">FEATURED SHAPE</span><h2>${safe(featuredTrack.title)}</h2><p>${safe(featuredTrack.artist)}</p>${radar(featuredTrack.scores, { className: "home-radar" })}<div class="feature-score">${["song", "vocal", "production", "overall"].map((field) => `<span>${field}<b>${rating(featuredTrack.scores[field])}</b></span>`).join("")}</div>${link(`/archive/tracks/${trackId(featuredTrack)}`, "EXPLORE TRACK →", "text-link")}</article><article><span class="eyebrow mono">FEATURED LANDSCAPE</span><h2>${safe(featuredAlbum.title)}</h2><p>${safe(featuredAlbum.artist)}</p>${waveform(draft)}${link(`/archive/albums/${slug(featuredAlbum.artist + "-" + featuredAlbum.title)}`, "EXPLORE ALBUM →", "text-link")}</article></section><section class="home-section enter-archive"><span class="eyebrow mono">ENTER THE ARCHIVE</span><div>${[["TRACKS", "/archive/tracks"], ["ALBUMS", "/archive/albums"], ["ARTISTS", "/archive/artists"]].map(([label, href]) => link(href, label + " →")).join("")}</div></section><section class="short-manifesto"><p>Music can be minimal or maximal, familiar or surprising. The only question is whether it stays alive.</p>${link("/taste", "ABOUT THIS ARCHIVE", "text-link")}</section>`;
};
