import { rating, safe, storage } from "../music/data.js";
import { link, pageHeader } from "../layout/shell.js";
import { rediscoveryCandidates } from "../music/analysis.js";
import { insightLabel, insightTagsOf } from "../music/insights.js";
import { listeningPortrait } from "../music/portrait.js";

const journalKey = "how-i-hear-music:journal:v1";
const awardsKey = "how-i-hear-music:personal-awards:v1";
const entriesForYear = (year) => storage.get(journalKey, []).filter((entry) => Number.isFinite(new Date(entry.at).getTime()) && new Date(entry.at).getFullYear() === year);
const scoreOf = (entry) => { const value = entry.type === "album" ? entry.overall : entry.scores?.overall; return value === null || value === undefined || value === "" ? NaN : Number(value); };
const best = (entries) => entries.filter((entry) => Number.isFinite(scoreOf(entry))).sort((a, b) => scoreOf(b) - scoreOf(a))[0] || null;
const evidence = (label, entry, value, note = "") => `<article><span class="mono">${safe(label)}</span>${entry ? `<strong>${safe(value)}</strong><h2>${safe(entry.title)}</h2><p>${entry.artist ? safe(entry.artist) : ""}${entry.artist && note ? " · " : ""}${note ? safe(note) : ""}</p>` : `<strong>—</strong><h2>Not enough evidence</h2><p>${safe(note)}</p>`}</article>`;

const ratingChanges = (entries) => {
  const groups = new Map();
  entries.filter((entry) => entry.type === "rating" && entry.trackId && Number.isFinite(scoreOf(entry))).forEach((entry) => groups.set(entry.trackId, [...(groups.get(entry.trackId) || []), entry]));
  return [...groups.values()].filter((group) => group.length > 1).map((group) => {
    const ordered = group.sort((a, b) => new Date(a.at) - new Date(b.at));
    return { entry: ordered.at(-1), delta: scoreOf(ordered.at(-1)) - scoreOf(ordered[0]) };
  });
};

export const journal = () => {
  const entries = storage.get(journalKey, []); const year = new Date().getFullYear(); const rediscovery = rediscoveryCandidates({ entries })[0];
  const rediscover = rediscovery ? `<section class="rediscover"><div><span class="mono">REDISCOVER · ${rediscovery.ageMonths} MONTHS AGO</span><h2>${safe(rediscovery.track.title)}</h2><p>${safe(rediscovery.track.artist)}</p></div><strong>${rating(rediscovery.entry.scores?.overall)}</strong><div class="rediscover-actions">${link(`/rate/track/${encodeURIComponent(rediscovery.entry.trackId)}`, "RATE AGAIN", "button primary")}<button class="button" type="button" data-skip-rediscovery="${safe(rediscovery.entry.trackId)}">SKIP FOR NOW</button></div></section>` : `<section class="rediscover rediscover-empty"><span class="mono">REDISCOVER</span><p>No archived rating is six months old yet.</p></section>`;
  return `${pageHeader("JOURNAL", "Taste over time.", "The archive records what stays. Journal records what changes.")}${rediscover}<div class="journal-year-link"><span class="mono">ANNUAL INDEX</span>${link(`/journal/year/${year}`, `${year} IN MUSIC →`, "text-link")}</div><section class="journal-list">${entries.length ? entries.map((entry) => { const tags = insightTagsOf(entry); return `<article><time class="mono">${new Date(entry.at).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}</time><div><span class="mono">${entry.type === "album" ? "ALBUM COMPLETED" : "RATING SAVED"}</span><h2>${safe(entry.title)}</h2>${tags.length ? `<p class="journal-reasons mono">${tags.map((tag) => safe(insightLabel[tag])).join(" · ")}</p>` : ""}${entry.moment?.timestamp && entry.moment?.note ? `<blockquote><b>${safe(entry.moment.timestamp)}</b> — ${safe(entry.moment.note)}</blockquote>` : ""}${entry.note ? `<p class="journal-note">${safe(entry.note)}</p>` : ""}<p class="journal-byline">${safe(entry.artist || "")}</p></div><strong>${entry.type === "album" ? rating(entry.overall) : rating(entry.scores?.overall)}</strong></article>`; }).join("") : `<article class="journal-empty"><span class="mono">NO ENTRIES YET</span><h2>The timeline begins with a saved rating.</h2><p>Rate a track or complete an album session to create the first entry.</p>${link("/rate", "BEGIN A RATING →", "text-link")}</article>`}</section>`;
};

export const bindJournal = (path, navigate) => {
  if (path !== "/journal") return;
  document.querySelector("[data-skip-rediscovery]")?.addEventListener("click", (event) => { const id = event.currentTarget.dataset.skipRediscovery; storage.set("how-i-hear-music:rediscovery-skips:v1", { ...storage.get("how-i-hear-music:rediscovery-skips:v1", {}), [id]: new Date().toISOString() }); navigate("/journal"); });
};

export const yearInMusic = (year) => {
  const entries = entriesForYear(year); const tracks = entries.filter((entry) => entry.type === "rating"); const albums = entries.filter((entry) => entry.type === "album");
  const highestTrack = best(tracks); const highestAlbum = best(albums); const scoredTracks = tracks.filter((entry) => Number.isFinite(scoreOf(entry))); const average = scoredTracks.length ? scoredTracks.reduce((sum, entry) => sum + scoreOf(entry), 0) / scoredTracks.length : null;
  const reasonCounts = new Map(); tracks.flatMap(insightTagsOf).forEach((reason) => reasonCounts.set(reason, (reasonCounts.get(reason) || 0) + 1));
  const commonReason = [...reasonCounts].sort((a, b) => b[1] - a[1])[0] || null; const changes = ratingChanges(tracks); const grower = changes.filter((item) => item.delta > 0).sort((a, b) => b.delta - a.delta)[0]; const disappointment = changes.filter((item) => item.delta < 0).sort((a, b) => a.delta - b.delta)[0];
  const discoveries = tracks.filter((entry) => entry.source && entry.source !== "archive").sort((a, b) => new Date(a.at) - new Date(b.at)); const discovery = discoveries[0] || null;
  const strange = scoredTracks.map((entry) => { const dimensions = [entry.scores?.song, entry.scores?.vocal, entry.scores?.production].map(Number).filter(Number.isFinite); return { entry, gap: dimensions.length === 3 ? Math.abs(scoreOf(entry) - dimensions.reduce((sum, value) => sum + value, 0) / 3) : -1 }; }).filter((item) => item.gap >= 0).sort((a, b) => b.gap - a.gap)[0];
  return `${pageHeader(`${year} IN MUSIC`, entries.length ? "A year described by listening evidence." : "The year is waiting for its first entry.", "No missing score, timestamp or discovery is inferred.", link(`/journal/year/${year}/portrait`, "VIEW LISTENING PORTRAIT", "button"))}<section class="year-lead"><span class="mono">YEAR AT A GLANCE</span><strong>${average === null ? "—" : rating(average)}</strong><p>AVERAGE TRACK RATING · ${scoredTracks.length} SAVED ${scoredTracks.length === 1 ? "RATING" : "RATINGS"}</p></section><section class="year-grid">${evidence("HIGHEST TRACK", highestTrack, highestTrack ? rating(scoreOf(highestTrack)) : "", "highest saved Overall")}${evidence("HIGHEST ALBUM", highestAlbum, highestAlbum ? rating(scoreOf(highestAlbum)) : "", "highest saved album Overall")}${evidence("BIGGEST GROWER", grower?.entry, grower ? `+${rating(grower.delta)}` : "", grower ? "first-to-latest Overall" : "Requires two ratings of the same track.")}${evidence("BIGGEST DISAPPOINTMENT", disappointment?.entry, disappointment ? rating(disappointment.delta) : "", disappointment ? "first-to-latest Overall" : "Requires a negative change across two ratings.")}${evidence("NEW DISCOVERY", discovery, discovery?.artist || "", discovery ? "first rated non-Archive import this year" : "Requires a rated imported record.")}${evidence("MOST COMMON REASON", commonReason ? { title: insightLabel[commonReason[0]] || commonReason[0], artist: "" } : null, commonReason ? `${commonReason[1]}×` : "", commonReason ? "counted from saved listening reasons" : "Save a listening reason with a rating.")}${evidence("STRANGEST RATING", strange?.entry, strange ? rating(strange.gap) : "", strange ? "gap between Overall and the mean of Song, Vocal and Production" : "Requires all four rating dimensions.")}</section>${awardsForm(year, entries)}<footer class="year-method"><span class="mono">METHOD</span><p>Grower and disappointment compare the first and latest saved Overall for the same track. New discovery means the first rated record imported from outside the canonical Archive. “Strangest” means the largest absolute gap between Overall and the mean of the other three dimensions. Awards remain unpublished until manually selected.</p></footer>`;
};

const uniqueEntries = (entries) => { const seen = new Set(); return entries.filter((entry) => { const id = entry.trackId || entry.albumId || `${entry.title}-${entry.artist}`; if (seen.has(id)) return false; seen.add(id); return true; }); };
const byDimension = (entries, field) => uniqueEntries(entries.filter((entry) => Number.isFinite(Number(entry.scores?.[field]))).sort((a, b) => Number(b.scores[field]) - Number(a.scores[field]))).slice(0, 6);
const awardsForm = (year, entries) => {
  const tracks = entries.filter((entry) => entry.type === "rating"); const albums = entries.filter((entry) => entry.type === "album"); const changes = ratingChanges(tracks).filter((item) => item.delta > 0).sort((a, b) => b.delta - a.delta).map((item) => item.entry); const confusing = tracks.map((entry) => { const parts = [entry.scores?.song, entry.scores?.vocal, entry.scores?.production].map(Number); return { entry, gap: parts.every(Number.isFinite) ? Math.abs(Number(entry.scores?.overall) - parts.reduce((sum, value) => sum + value, 0) / 3) : -1 }; }).filter((item) => item.gap >= 0).sort((a, b) => b.gap - a.gap).map((item) => item.entry);
  const categories = [["best-melody", "BEST MELODY", byDimension(tracks, "song")], ["best-arrangement", "BEST ARRANGEMENT", byDimension(tracks, "production")], ["best-vocal", "BEST VOCAL INTERPRETATION", byDimension(tracks, "vocal")], ["best-surprise", "BEST SURPRISE", uniqueEntries(tracks.filter((entry) => insightTagsOf(entry).includes("surprise")))], ["biggest-grower", "BIGGEST GROWER", uniqueEntries(changes)], ["most-confusing", "MOST CONFUSING SONG", uniqueEntries(confusing).slice(0, 6)], ["best-moment", "BEST ONE PERFECT MOMENT", uniqueEntries(tracks.filter((entry) => entry.moment?.timestamp && entry.moment?.note))], ["best-album", "BEST ALBUM LANDSCAPE", uniqueEntries(albums).slice(0, 6)]];
  const saved = storage.get(awardsKey, {})[year] || {};
  const confirmed = categories.filter(([id]) => saved[id]).map(([id, label]) => `<article><span class="mono">${safe(label)}</span><h3>${safe(saved[id].title)}</h3><p>${safe(saved[id].artist || "")}</p></article>`).join("");
  return `<section class="personal-awards"><div><span class="mono">PERSONAL MUSIC AWARDS</span><h2>Suggestions are evidence. Winners are a decision.</h2><p>Every category may remain unselected.</p>${confirmed ? `<div class="award-winners">${confirmed}</div>` : ""}</div><form data-awards-year="${year}">${categories.map(([id, label, candidates]) => `<label><span>${label}</span><select name="${id}"><option value="">NO SELECTION</option>${candidates.map((entry) => { const value = entry.trackId || entry.albumId || `${entry.title}-${entry.artist}`; return `<option value="${safe(value)}" data-title="${safe(entry.title)}" data-artist="${safe(entry.artist || "")}"${saved[id]?.id === value ? " selected" : ""}>${safe(entry.title)}${entry.artist ? ` — ${safe(entry.artist)}` : ""}</option>`; }).join("")}</select></label>`).join("")}<button class="button primary" type="submit">CONFIRM AWARDS</button><p data-awards-status>${Object.keys(saved).length ? "Confirmed selections saved locally." : "No winners confirmed."}</p></form></section>`;
};

export const annualPortrait = (year) => { const entries = entriesForYear(year); const tracks = entries.filter((entry) => entry.type === "rating" && Number.isFinite(Number(entry.scores?.overall))); const albums = entries.filter((entry) => entry.type === "album" && Array.isArray(entry.tracks)); return `${pageHeader(`${year} LISTENING PORTRAIT`, tracks.length ? "A year rendered as listening geometry." : "This portrait is waiting for ratings.", "Layered Track Radars and Album landscapes are sampled from saved evidence only.")}${listeningPortrait({ tracks, albums, year: String(year) })}`; };

export const bindYear = (path, navigate) => {
  const match = path.match(/^\/journal\/year\/(\d{4})$/); if (!match) return; const year = match[1]; const form = document.querySelector("[data-awards-year]");
  form?.addEventListener("submit", (event) => { event.preventDefault(); const selections = {}; form.querySelectorAll("select").forEach((select) => { const option = select.selectedOptions[0]; if (select.value) selections[select.name] = { id: select.value, title: option.dataset.title, artist: option.dataset.artist, confirmedAt: new Date().toISOString() }; }); storage.set(awardsKey, { ...storage.get(awardsKey, {}), [year]: selections }); navigate(path); });
};
