import { allAlbums, allArtists, allTracks, findAlbum, findArtist, findTrack, rating, safe, slug, storage, trackId } from "../music/data.js";
import { link, pageHeader } from "../layout/shell.js";
import { rediscoveryCandidates } from "../music/analysis.js";
import { insightLabel, insightTags, insightTagsOf } from "../music/insights.js";
import { listeningPortrait } from "../music/portrait.js";
import { archiveEntropy, entropyNarrative } from "../music/entropy.js";
import { addMemoryEntry, allMemoryEntries, memoryZones, removeMemoryEntry } from "../music/memory.js";
import { journalEntry, readJournal, updateJournalEntry } from "../music/journal.js";

const journalKey = "how-i-hear-music:journal:v1";
const awardsKey = "how-i-hear-music:personal-awards:v1";
const entriesForYear = (year) => readJournal().filter((entry) => Number.isFinite(new Date(entry.at).getTime()) && new Date(entry.at).getFullYear() === year);
const scoreOf = (entry) => { const value = entry.type === "album" ? entry.overall : entry.scores?.overall; return value === null || value === undefined || value === "" ? NaN : Number(value); };
const best = (entries) => entries.filter((entry) => Number.isFinite(scoreOf(entry))).sort((a, b) => scoreOf(b) - scoreOf(a))[0] || null;
const evidence = (label, entry, value, note = "", oldValue = "") => `<article><span class="mono">${safe(label)}</span>${entry ? `<strong${oldValue !== "" ? ` class="score-overprint" data-old-score="${safe(oldValue)}"` : ""}>${safe(value)}</strong><h2>${safe(entry.title)}</h2><p>${entry.artist ? safe(entry.artist) : ""}${entry.artist && note ? " · " : ""}${note ? safe(note) : ""}</p>` : `<strong>—</strong><h2>Not enough evidence</h2><p>${safe(note)}</p>`}</article>`;

const ratingChanges = (entries) => {
  const groups = new Map();
  entries.filter((entry) => entry.type === "rating" && entry.trackId && Number.isFinite(scoreOf(entry))).forEach((entry) => groups.set(entry.trackId, [...(groups.get(entry.trackId) || []), entry]));
  return [...groups.values()].filter((group) => group.length > 1).map((group) => {
    const ordered = group.sort((a, b) => new Date(a.at) - new Date(b.at));
    return { entry: ordered.at(-1), first:scoreOf(ordered[0]), latest:scoreOf(ordered.at(-1)), delta: scoreOf(ordered.at(-1)) - scoreOf(ordered[0]) };
  });
};

export const journal = (root = "/journal") => {
  const entries = readJournal(); const year = new Date().getFullYear(); const rediscovery = rediscoveryCandidates({ entries })[0]; const merged = root === "/taste/journal";
  const rediscover = rediscovery ? `<section class="rediscover"><div><span class="mono">REDISCOVER · ${rediscovery.ageMonths} MONTHS AGO</span><h2>${safe(rediscovery.track.title)}</h2><p>${safe(rediscovery.track.artist)}</p></div><strong>${rating(rediscovery.entry.scores?.overall)}</strong><div class="rediscover-actions">${link(`/rate/track/${encodeURIComponent(rediscovery.entry.trackId)}`, "RATE AGAIN", "button primary")}<button class="button" type="button" data-skip-rediscovery="${safe(rediscovery.entry.trackId)}">SKIP FOR NOW</button></div></section>` : `<section class="rediscover rediscover-empty"><span class="mono">REDISCOVER</span><p>No archived rating is six months old yet.</p></section>`;
  const recent = entries.slice().sort((left, right) => new Date(right.at || 0) - new Date(left.at || 0)).slice(0, 6);
  const recentMarkup = recent.length ? `<section class="journal-recent"><div class="journal-recent-head"><span class="mono">RECENT CHANGES</span><span class="mono">${recent.length} MOST RECENT</span></div>${recent.map((entry) => { const score = scoreOf(entry); const label = entry.type === "album" ? "ALBUM" : "RATING"; return `<article><time class="mono">${safe(new Date(entry.at).toLocaleDateString())}</time><div><strong>${safe(entry.title)}</strong><p>${safe(entry.artist || label)}${entry.note ? ` · ${safe(entry.note)}` : ""}</p></div><b>${rating(score)}</b>${entry.id ? link(`${root}/edit/${encodeURIComponent(entry.id)}`, "EDIT", "text-link") : ""}</article>`; }).join("")}</section>` : `<section class="journal-recent journal-empty"><span class="mono">RECENT CHANGES</span><p>No saved listening changes yet.</p></section>`;
  return `${pageHeader(merged ? "TASTE / JOURNAL" : "JOURNAL", "Taste over time.", "The archive records what stays. Journal records what changes.")}<nav class="journal-analysis-index" aria-label="Listening memory analysis">${link(`${root}/memory-palace`, "MEMORY PALACE →")}${link(`${root}/entropy`, "ARCHIVE ENTROPY →")}</nav>${rediscover}${recentMarkup}<div class="journal-year-link"><span class="mono">ANNUAL INDEX</span>${link(`${root}/year/${year}`, `${year} IN MUSIC →`, "text-link")}</div>`;
};

const scoreInput = (name, label, value) => `<label><span>${label}</span><input name="${name}" type="number" min="0" max="11" step="0.1" value="${value === null || value === undefined ? "" : safe(value)}"></label>`;
export const journalEdit = (id, root = "/journal") => {
  const entry = journalEntry(id); if (!entry) return `${pageHeader("JOURNAL / CORRECTION", "Entry not found.", "It may already have been removed.")}`;
  const scores = entry.type === "rating" ? [scoreInput("song", "SONG", entry.scores?.song), scoreInput("vocal", "VOCAL", entry.scores?.vocal), scoreInput("production", "PRODUCTION", entry.scores?.production), scoreInput("overall", "OVERALL", entry.scores?.overall)].join("") : scoreInput("overall", "ALBUM OVERALL", entry.overall);
  const reasons = insightTagsOf(entry);
  return `${pageHeader("JOURNAL / CORRECTION", safe(entry.title), "This edits one historical snapshot only. Record identity stays linked to the original Track or Album.")}<form class="journal-edit-form" data-journal-id="${safe(entry.id)}"><div class="journal-identity"><span class="mono">LOCKED RECORD</span><strong>${safe(entry.title)}</strong><p>${safe(entry.artist || "Artist not recorded")}</p></div><div class="journal-edit-fields">${scores}<label><span>MOMENT TIME</span><input name="momentTimestamp" inputmode="numeric" maxlength="5" placeholder="2:47" value="${safe(entry.moment?.timestamp || "")}"></label><label><span>MOMENT NOTE</span><input name="momentNote" maxlength="160" value="${safe(entry.moment?.note || "")}"></label>${entry.type === "rating" ? `<fieldset class="journal-reason-edit"><legend class="mono">WHY THIS WORKED IN THIS SNAPSHOT</legend>${insightTags.map((tag) => `<label><input type="checkbox" name="reasons" value="${safe(tag)}"${reasons.includes(tag) ? " checked" : ""}><span>${safe(insightLabel[tag])}</span></label>`).join("")}</fieldset>` : ""}<label class="journal-edit-note"><span>HISTORICAL NOTE</span><textarea name="note" rows="5" maxlength="600">${safe(entry.note || "")}</textarea></label></div><div class="journal-edit-actions"><button class="button primary" type="submit">SAVE HISTORY CORRECTION</button>${link(root, "CANCEL", "button")}</div><p data-journal-edit-status>${entry.revisedAt ? `Corrected ${safe(new Date(entry.revisedAt).toLocaleString())} · revision ${entry.revisionCount || 1}.` : "No correction recorded yet."}</p></form>`;
};

export const bindJournal = (path, navigate) => {
  const inMergedTaste = path === "/taste/journal" || path.startsWith("/taste/journal/");
  const journalRoot = inMergedTaste ? "/taste/journal" : "/journal";
  if (path === "/journal" || path === "/taste/journal") document.querySelector("[data-skip-rediscovery]")?.addEventListener("click", (event) => { const id = event.currentTarget.dataset.skipRediscovery; storage.set("how-i-hear-music:rediscovery-skips:v1", { ...storage.get("how-i-hear-music:rediscovery-skips:v1", {}), [id]: new Date().toISOString() }); navigate(journalRoot); });
  if (path.startsWith("/journal/edit/") || path.startsWith("/taste/journal/edit/")) document.querySelector(".journal-edit-form")?.addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { updateJournalEntry(form.dataset.journalId, { ...Object.fromEntries(data), reasons: data.getAll("reasons") }); navigate(journalRoot); } catch (error) { form.querySelector("[data-journal-edit-status]").textContent = error.message; } });
  if (path !== "/journal/memory-palace" && path !== "/taste/journal/memory-palace") return;
  const form = document.querySelector(".memory-form"); const type = form?.elements.entityType; const entity = form?.elements.entityId;
  type?.addEventListener("change", () => { entity.innerHTML = memoryOptions(type.value); });
  form?.addEventListener("submit", (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(form)); try { addMemoryEntry(values); navigate(path); } catch (error) { form.querySelector("[data-memory-status]").textContent = error.message; } });
  document.querySelector(".memory-palace")?.addEventListener("click", (event) => { const button = event.target.closest("[data-remove-memory]"); if (!button) return; removeMemoryEntry(button.dataset.removeMemory); navigate(path); });
};

const entropyChart = (series) => {
  if (!series.length) return ""; const width = 720; const height = 260; const points = series.map((item, index) => `${60 + index / Math.max(1, series.length - 1) * 600},${220 - item.index * 160}`).join(" ");
  return `<svg class="entropy-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Archive entropy over time"><line x1="60" y1="220" x2="660" y2="220"></line><polyline points="${points}"></polyline>${series.map((item, index) => { const x = 60 + index / Math.max(1, series.length - 1) * 600; const y = 220 - item.index * 160; return `<g transform="translate(${x} ${y})"><circle r="5"></circle><text y="-14" text-anchor="middle">${Math.round(item.index * 100)}</text><text y="28" text-anchor="middle">${safe(item.period)}</text></g>`; }).join("")}</svg>`;
};

export const entropyPage = () => {
  const series = archiveEntropy({ entries: storage.get(journalKey, []) }); const latest = series.at(-1); const metrics = latest ? [["ARTIST CONCENTRATION", latest.artistConcentration], ["TRAIT DIVERSITY", latest.traitDiversity], ["ERA SPREAD", latest.eraSpread], ["ALBUM DEPTH", latest.albumDepth], ["EXPLORATION RATE", latest.explorationRate]] : [];
  const available = latest ? metrics.filter(([, value]) => value !== null).map(([label]) => label).join(" · ") : "";
  return `${pageHeader("JOURNAL / ARCHIVE ENTROPY", "Is the archive widening?", "A higher number means the archive is more distributed. A lower number means it is more specialized. Neither is better.")}${series.length ? `<section class="entropy-lead"><div><span class="mono">LATEST · ${safe(latest.period)}</span><strong>${Math.round(latest.index * 100)}</strong><p>${safe(entropyNarrative(series))}</p><small class="mono">${latest.evidenceCount} CURRENT TRACKS · ${metrics.filter(([, value]) => value !== null).length} OF 5 DIMENSIONS AVAILABLE</small></div>${entropyChart(series)}</section><dl class="entropy-metrics">${metrics.map(([label, value]) => `<div><dt>${label}</dt><dd>${value === null ? "—" : Math.round(value * 100)}</dd></div>`).join("")}</dl><p class="entropy-method"><b>AVAILABLE:</b> ${safe(available)}. Calculated from cumulative saved Journal ratings by quarter. The 0–100 index is a directional summary, not a precise measurement. Missing tags, years or album metadata stay absent from the relevant dimension.${latest.evidenceCount < 10 ? " This is a low-evidence baseline and may move sharply with a few ratings." : ""}</p>` : `<section class="analysis-empty"><span class="mono">NO TIME SERIES YET</span><h2>Entropy begins after three dated track ratings.</h2><p>The first qualifying quarter establishes a baseline; later quarters reveal direction.</p>${link("/rate", "SAVE A RATING →", "text-link")}</section>`}`;
};

const memoryEntity = (entry) => {
  if (entry.entityType === "album") { const record = findAlbum(entry.entityId); return record ? { title: record.title, byline: record.artist, href: `/archive/albums/${entry.entityId}` } : null; }
  if (entry.entityType === "artist") { const record = findArtist(entry.entityId); return record ? { title: record.name, byline: record.role || "Artist", href: `/archive/artists/${entry.entityId}` } : null; }
  const record = findTrack(entry.entityId); return record ? { title: record.title, byline: record.artist, href: `/archive/tracks/${trackId(record)}` } : null;
};
const memoryOptions = (type) => {
  const rows = type === "album" ? allAlbums().map((item) => [item.id || slug(item.artist + "-" + item.title), `${item.title} — ${item.artist}`]) : type === "artist" ? allArtists().map((item) => [item.id, item.name]) : allTracks().filter((item) => type === "version" ? item.versionType : true).map((item) => [trackId(item), `${item.title} — ${item.artist}${item.versionType ? ` · ${item.versionType}` : ""}`]);
  return rows.map(([id, label]) => `<option value="${safe(id)}">${safe(label)}</option>`).join("");
};
export const memoryPalace = () => {
  const entries = allMemoryEntries().sort((a, b) => Number(b.importance || 0) - Number(a.importance || 0) || new Date(b.date || b.createdAt || 0) - new Date(a.date || a.createdAt || 0));
  return `${pageHeader("JOURNAL / MEMORY PALACE", "A spatial index of what stayed.", "A two-dimensional archive of discoveries, growers, moments and turning points—not a literal room.")}<section class="memory-palace">${memoryZones.map(([zone, label], index) => { const items = entries.filter((entry) => entry.zone === zone).map((entry) => ({ entry, entity: memoryEntity(entry) })).filter((item) => item.entity); return `<article class="memory-zone memory-zone-${index + 1}"><span class="mono">${String(index + 1).padStart(2, "0")} · ${label}</span>${items.length ? `<div>${items.map(({ entry, entity }) => `<details><summary><b>${safe(entity.title)}</b><small>${safe(entity.byline)} · IMPORTANCE ${entry.importance || 3}/5</small></summary>${entry.note ? `<p>${safe(entry.note)}</p>` : ""}<footer>${link(entity.href, "OPEN RECORD →", "text-link")}<span class="mono">${entry.source === "manual" ? "PLACED MANUALLY" : "DERIVED FROM SAVED EVIDENCE"}</span>${entry.source === "manual" ? `<button type="button" data-remove-memory="${safe(entry.id)}">REMOVE</button>` : ""}</footer></details>`).join("")}</div>` : `<p>No memory placed here yet.</p>`}</article>`; }).join("")}</section><form class="memory-form"><span class="mono">PLACE A MEMORY</span><label><span>TYPE</span><select name="entityType"><option value="track">TRACK</option><option value="album">ALBUM</option><option value="artist">ARTIST</option><option value="version">VERSION</option></select></label><label><span>RECORD</span><select name="entityId" required>${memoryOptions("track")}</select></label><label><span>ZONE</span><select name="zone">${memoryZones.map(([id, label]) => `<option value="${id}">${label}</option>`).join("")}</select></label><label><span>DATE</span><input type="date" name="date"></label><label class="memory-note"><span>WHY IT BELONGS HERE</span><textarea name="note" maxlength="240" rows="3"></textarea></label><label><span>IMPORTANCE</span><input type="range" name="importance" min="1" max="5" value="3"></label><button class="button primary" type="submit">PLACE IN ARCHIVE</button><p data-memory-status>Manual entries stay in this browser and in local backup.</p></form>`;
};

export const yearInMusic = (year, root = "/journal") => {
  const entries = entriesForYear(year); const tracks = entries.filter((entry) => entry.type === "rating"); const albums = entries.filter((entry) => entry.type === "album");
  const highestTrack = best(tracks); const highestAlbum = best(albums); const scoredTracks = tracks.filter((entry) => Number.isFinite(scoreOf(entry))); const average = scoredTracks.length ? scoredTracks.reduce((sum, entry) => sum + scoreOf(entry), 0) / scoredTracks.length : null;
  const reasonCounts = new Map(); tracks.flatMap(insightTagsOf).forEach((reason) => reasonCounts.set(reason, (reasonCounts.get(reason) || 0) + 1));
  const commonReason = [...reasonCounts].sort((a, b) => b[1] - a[1])[0] || null; const changes = ratingChanges(tracks); const grower = changes.filter((item) => item.delta > 0).sort((a, b) => b.delta - a.delta)[0]; const disappointment = changes.filter((item) => item.delta < 0).sort((a, b) => a.delta - b.delta)[0];
  const discoveries = tracks.filter((entry) => entry.source && entry.source !== "archive").sort((a, b) => new Date(a.at) - new Date(b.at)); const discovery = discoveries[0] || null;
  const strange = scoredTracks.map((entry) => { const dimensions = [entry.scores?.song, entry.scores?.vocal, entry.scores?.production].map(Number).filter(Number.isFinite); return { entry, gap: dimensions.length === 3 ? Math.abs(scoreOf(entry) - dimensions.reduce((sum, value) => sum + value, 0) / 3) : -1 }; }).filter((item) => item.gap >= 0).sort((a, b) => b.gap - a.gap)[0];
  return `${pageHeader(`${year} IN MUSIC`, entries.length ? "A year described by listening evidence." : "The year is waiting for its first entry.", "No missing score, timestamp or discovery is inferred.", link(`${root}/year/${year}/portrait`, "VIEW LISTENING PORTRAIT", "button"))}<section class="year-lead"><span class="mono">YEAR AT A GLANCE</span><strong>${average === null ? "—" : rating(average)}</strong><p>AVERAGE TRACK RATING · ${scoredTracks.length} SAVED ${scoredTracks.length === 1 ? "RATING" : "RATINGS"}</p></section><section class="year-grid">${evidence("HIGHEST TRACK", highestTrack, highestTrack ? rating(scoreOf(highestTrack)) : "", "highest saved Overall")}${evidence("HIGHEST ALBUM", highestAlbum, highestAlbum ? rating(scoreOf(highestAlbum)) : "", "highest saved album Overall")}${evidence("BIGGEST GROWER", grower?.entry, grower ? rating(grower.latest) : "", grower ? `${rating(grower.first)} → ${rating(grower.latest)} · +${rating(grower.delta)}` : "Requires two ratings of the same track.", grower ? rating(grower.first) : "")}${evidence("BIGGEST DISAPPOINTMENT", disappointment?.entry, disappointment ? rating(disappointment.latest) : "", disappointment ? `${rating(disappointment.first)} → ${rating(disappointment.latest)} · ${rating(disappointment.delta)}` : "Requires a negative change across two ratings.", disappointment ? rating(disappointment.first) : "")}${evidence("NEW DISCOVERY", discovery, discovery?.artist || "", discovery ? "first rated non-Archive import this year" : "Requires a rated imported record.")}${evidence("MOST COMMON REASON", commonReason ? { title: insightLabel[commonReason[0]] || commonReason[0], artist: "" } : null, commonReason ? `${commonReason[1]}×` : "", commonReason ? "counted from saved listening reasons" : "Save a listening reason with a rating.")}${evidence("STRANGEST RATING", strange?.entry, strange ? rating(strange.gap) : "", strange ? "gap between Overall and the mean of Song, Vocal and Production" : "Requires all four rating dimensions.")}</section>${awardsForm(year, entries)}<footer class="year-method"><span class="mono">METHOD</span><p>Grower and disappointment compare the first and latest saved Overall for the same track. New discovery means the first rated record imported from outside the canonical Archive. “Strangest” means the largest absolute gap between Overall and the mean of the other three dimensions. Awards remain unpublished until manually selected.</p></footer>`;
};

const uniqueEntries = (entries) => { const seen = new Set(); return entries.filter((entry) => { const id = entry.trackId || entry.albumId || `${entry.title}-${entry.artist}`; if (seen.has(id)) return false; seen.add(id); return true; }); };
const byDimension = (entries, field) => uniqueEntries(entries.filter((entry) => Number.isFinite(Number(entry.scores?.[field]))).sort((a, b) => Number(b.scores[field]) - Number(a.scores[field]))).slice(0, 6);
const awardsForm = (year, entries) => {
  const tracks = entries.filter((entry) => entry.type === "rating"); const albums = entries.filter((entry) => entry.type === "album"); const changes = ratingChanges(tracks).filter((item) => item.delta > 0).sort((a, b) => b.delta - a.delta).map((item) => item.entry); const confusing = tracks.map((entry) => { const parts = [entry.scores?.song, entry.scores?.vocal, entry.scores?.production].map(Number); return { entry, gap: parts.every(Number.isFinite) ? Math.abs(Number(entry.scores?.overall) - parts.reduce((sum, value) => sum + value, 0) / 3) : -1 }; }).filter((item) => item.gap >= 0).sort((a, b) => b.gap - a.gap).map((item) => item.entry);
  const categories = [["best-melody", "BEST MELODY", byDimension(tracks, "song")], ["best-arrangement", "BEST ARRANGEMENT", byDimension(tracks, "production")], ["best-vocal", "BEST VOCAL INTERPRETATION", byDimension(tracks, "vocal")], ["best-surprise", "BEST SURPRISE", uniqueEntries(tracks.filter((entry) => insightTagsOf(entry).includes("surprise")))], ["biggest-grower", "BIGGEST GROWER", uniqueEntries(changes)], ["most-confusing", "MOST CONFUSING SONG", uniqueEntries(confusing).slice(0, 6)], ["best-moment", "BEST ONE PERFECT MOMENT", uniqueEntries(tracks.filter((entry) => entry.moment?.timestamp && entry.moment?.note))], ["best-album", "BEST ALBUM LANDSCAPE", uniqueEntries(albums).slice(0, 6)]];
  const saved = storage.get(awardsKey, {})[year] || {};
  const confirmed = categories.filter(([id]) => saved[id]).map(([id, label]) => `<article><span class="mono">${safe(label)}</span><h3>${safe(saved[id].title)}</h3><p>${safe(saved[id].artist || "")}</p></article>`).join("");
  return `<section class="personal-awards"><div><span class="mono">PERSONAL MUSIC AWARDS</span><h2>Suggestions are evidence. Winners are a decision.</h2><p>Every category may remain unselected.</p>${confirmed ? `<div class="award-winners">${confirmed}</div>` : ""}</div><form data-awards-year="${year}">${categories.map(([id, label, candidates]) => `<label><span>${label}</span><select name="${id}"><option value="">NO SELECTION</option>${candidates.map((entry) => { const value = entry.trackId || entry.albumId || `${entry.title}-${entry.artist}`; return `<option value="${safe(value)}" data-title="${safe(entry.title)}" data-artist="${safe(entry.artist || "")}"${saved[id]?.id === value ? " selected" : ""}>${safe(entry.title)}${entry.artist ? ` — ${safe(entry.artist)}` : ""}</option>`; }).join("")}</select></label>`).join("")}<button class="button primary" type="submit">CONFIRM AWARDS</button><p data-awards-status>${Object.keys(saved).length ? "Confirmed selections saved locally." : "No winners confirmed."}</p></form></section>`;
};

export const annualPortrait = (year) => { const entries = entriesForYear(year); const tracks = entries.filter((entry) => entry.type === "rating" && Number.isFinite(Number(entry.scores?.overall))); const albums = entries.filter((entry) => entry.type === "album" && Array.isArray(entry.tracks)); return `${pageHeader(`${year} LISTENING PORTRAIT`, tracks.length ? "A year rendered as listening geometry." : "This portrait is waiting for ratings.", "Layered Track Radars and Album landscapes are sampled from saved evidence only.")}${listeningPortrait({ tracks, albums, year: String(year) })}`; };

export const bindYear = (path, navigate) => {
  const match = path.match(/^\/(?:journal|taste\/journal)\/year\/(\d{4})$/); if (!match) return; const year = match[1]; const form = document.querySelector("[data-awards-year]");
  form?.addEventListener("submit", (event) => { event.preventDefault(); const selections = {}; form.querySelectorAll("select").forEach((select) => { const option = select.selectedOptions[0]; if (select.value) selections[select.name] = { id: select.value, title: option.dataset.title, artist: option.dataset.artist, confirmedAt: new Date().toISOString() }; }); storage.set(awardsKey, { ...storage.get(awardsKey, {}), [year]: selections }); navigate(path); });
};
