import { safe } from "./data.js";
import { geometryFields, glyphPoints, terrainPoints } from "./geometry.js";

export const listeningPortrait = ({ tracks = [], albums = [], year = "ALL TIME" } = {}) => {
  const sampled = tracks.filter((track) => Number.isFinite(Number(track.scores?.overall))).sort((a, b) => Number(b.scores.overall) - Number(a.scores.overall)).slice(0, 24);
  const shapes = sampled.map((track, index) => { const radius = Math.max(72, 150 - index * 2.5); return `<polygon points="${glyphPoints(track.scores, 360, 238, radius)}" opacity="${(0.08 + (sampled.length - index) / Math.max(1, sampled.length) * .18).toFixed(2)}"><title>${safe(track.title)} — ${safe(track.artist)}</title></polygon>`; }).join("");
  const bands = albums.slice(0, 8).map((album, bandIndex) => { const terrain = terrainPoints(album.tracks || [], 560, 48, 0); if (!terrain) return ""; const points = terrain.split(" ").map((point) => { const [x, y] = point.split(",").map(Number); return `${80 + x},${420 + bandIndex * 14 + y * .42}`; }).join(" "); return `<polyline points="${points}" opacity="${.55 - bandIndex * .05}"><title>${safe(album.title)}</title></polyline>`; }).join("");
  const byArtist = new Map(); sampled.forEach((track) => byArtist.set(track.artist, [...(byArtist.get(track.artist) || []), track]));
  const signatures = [...byArtist].sort((a, b) => b[1].length - a[1].length).slice(0, 4).map(([artist, artistTracks], index) => { const scores = Object.fromEntries(geometryFields.map((field) => [field, artistTracks.reduce((sum, track) => sum + (Number(track.scores?.[field]) || 0), 0) / artistTracks.length])); const x = 90 + index * 72; return `<polygon points="${glyphPoints(scores, x, 96, 26)}"><title>${safe(artist)} signature</title></polygon>`; }).join("");
  return `<figure class="listening-portrait"><svg viewBox="0 0 720 580" role="img" aria-label="${safe(year)} listening portrait"><g class="portrait-signatures">${signatures}</g><g class="portrait-radars">${shapes}</g><g class="portrait-bands">${bands}</g><text x="40" y="48">${safe(year)}</text><text x="40" y="552">${sampled.length} TRACK GLYPHS · ${albums.length} ALBUM TERRAINS · ${Math.min(4, byArtist.size)} ARTIST SIGNATURES</text></svg><figcaption>Built only from saved geometry. Dense archives are sampled to keep the print legible.</figcaption></figure>`;
};
