import { safe } from "./data.js";

const radarPoint = (value, index, cx, cy, radius) => { const angle = -Math.PI / 2 + Math.PI * 2 * index / 4; const distance = Math.max(0, Math.min(11, Number(value) || 0)) / 11 * radius; return `${(cx + Math.cos(angle) * distance).toFixed(1)},${(cy + Math.sin(angle) * distance).toFixed(1)}`; };
export const listeningPortrait = ({ tracks = [], albums = [], year = "ALL TIME" } = {}) => {
  const sampled = tracks.filter((track) => Number.isFinite(Number(track.scores?.overall))).sort((a, b) => Number(b.scores.overall) - Number(a.scores.overall)).slice(0, 24);
  const shapes = sampled.map((track, index) => { const radius = 150 - index * 2.5; const points = ["song", "vocal", "production", "overall"].map((field, pointIndex) => radarPoint(track.scores[field], pointIndex, 360, 238, Math.max(72, radius))).join(" "); return `<polygon points="${points}" opacity="${(0.08 + (sampled.length - index) / Math.max(1, sampled.length) * .18).toFixed(2)}"><title>${safe(track.title)} — ${safe(track.artist)}</title></polygon>`; }).join("");
  const bands = albums.slice(0, 8).map((album, bandIndex) => { const values = (album.tracks || []).map((track) => Number(track.overall)).filter(Number.isFinite); if (values.length < 2) return ""; const yBase = 445 + bandIndex * 14; const points = values.map((value, index) => `${80 + index / Math.max(1, values.length - 1) * 560},${yBase - (value - 5) * 5}`).join(" "); return `<polyline points="${points}" opacity="${.55 - bandIndex * .05}"><title>${safe(album.title)}</title></polyline>`; }).join("");
  return `<figure class="listening-portrait"><svg viewBox="0 0 720 580" role="img" aria-label="${safe(year)} listening portrait"><g class="portrait-radars">${shapes}</g><g class="portrait-bands">${bands}</g><text x="40" y="48">${safe(year)}</text><text x="40" y="552">${sampled.length} TRACK SHAPES · ${albums.length} ALBUM LANDSCAPES</text></svg><figcaption>Built only from saved ratings. Dense archives are sampled to keep the print legible.</figcaption></figure>`;
};
