import { allArtists, allTracks, archiveVisibleAlbums, data, findTrack, rating, safe, storage, trackId } from "../music/data.js";
import { radar } from "../rating/visuals.js";
import { link, pageHeader } from "../layout/shell.js";
import { antiRecommendationPatterns, currentEvidence } from "../music/analysis.js";
import { insightLabel, insightStats } from "../music/insights.js";
import { readSonic, sonicDimensions } from "../music/sonic.js";
import { addTasteGroup, readTasteGroups, removeTasteGroup } from "../music/groups.js";
import { listeningPortrait } from "../music/portrait.js";
import { blindSpots, tasteDNA } from "../music/taste-dna.js";
import { tasteTraitMark } from "../music/geometry.js";

const mergedTasteSections = [
  ["OVERVIEW", "The shape of the archive, its method and its recurring signals.", [["LISTENING DNA", "/taste/dna"], ["LISTENING PORTRAIT", "/taste/portrait"], ["LISTENING PHILOSOPHY", "/taste/philosophy"], ["COMPARE WITH ME", "/taste/compare"]]],
  ["JOURNAL", "The time layer: what changed, resurfaced and earned a place in memory.", [["LISTENING JOURNAL", "/taste/journal"], ["ANNUAL INDEX", `/taste/journal/year/${new Date().getFullYear()}`]]],
  ["INSIGHTS", "Transparent analysis of the boundaries, movement and gaps in your listening.", [["SONIC MAP", "/taste/sonic-map"], ["BOUNDARIES", "/taste/anti-recommendation"], ["MEMORY PALACE", "/taste/journal/memory-palace"], ["ARCHIVE ENTROPY", "/taste/journal/entropy"], ["TASTE CONSTELLATION", "/taste/family-tree"]]],
];
export const tasteHome = () => `${pageHeader("TASTE", "How I hear music.", "One personal listening archive: its overview, history and transparent insights.")}<section class="taste-merged-index" aria-label="Personal listening archive">${mergedTasteSections.map(([title, copy, items]) => `<article class="taste-merged-section"><span class="mono">${title}</span><p>${copy}</p><nav aria-label="${title}">${items.map(([label, href], index) => link(href, `${String(index + 1).padStart(2, "0")} / ${label} →`, "taste-merged-link")).join("")}</nav></article>`).join("")}</section>`;

export const philosophy = () => `${pageHeader("TASTE / PHILOSOPHY", "Every element needs a reason.", data.profile.methodCopy)}<div class="essay-stack"><article><span>01</span><h2>Melody opens the door.</h2><p>${safe(data.profile.firstGateCopy)}</p></article>${data.profile.listeningOrder.map((item, index) => `<article><span>${String(index + 2).padStart(2, "0")}</span><h2>${safe(item.name)}</h2><p>${safe(item.note)}</p></article>`).join("")}<article><span>06</span><h2>Surprise belongs to the song.</h2><p>${safe(data.profile.surpriseFactor.latePayoffNote)}</p></article><article><span>07</span><h2>The human voice stays human.</h2><p>${safe(data.profile.humanVoice.refusal)}</p></article></div>`;

const profileSummary = () => {
  const traits = [["MELODY", "high priority"], ["PRODUCTION", "high priority"], ["VOCAL SKILL", "appreciated, not decisive"], ["HARMONY", "strong affinity"], ["GROOVE", "strong affinity"], ["COMPLEXITY", "context dependent"]];
  const stats = insightStats(currentEvidence());
  return `<section class="taste-profile-summary"><span class="mono">LISTENING PROFILE</span><div class="profile-grid">${traits.map(([label, note]) => `<article><span class="mono">${label}</span><strong>${note}</strong></article>`).join("")}</div><section class="insight-analysis"><span class="mono">WHAT MAKES 9+ TRACKS WORK?</span>${stats.length ? `<div>${stats.map((item) => `<p><strong>${Math.round(item.count / item.total * 100)}%</strong><span>${safe(insightLabel[item.tag])}</span><small>${item.count} OF ${item.total} TAGGED TRACKS</small></p>`).join("")}</div>` : `<h2>Not enough explicit listening reasons yet.</h2>`}</section></section>`;
};

const goodNotMineMarkup = () => {
  const entries = data.songs.scoreReflections.examples.map((example) => data.songs.entries.find((entry) => entry.title === example.title)).filter(Boolean);
  return `<section class="taste-boundary-good"><span class="mono">GOOD ≠ MINE</span><h2>I know it's good. It's just not mine.</h2><p>Technical admiration and personal resonance do not need to agree.</p><div class="good-not-mine">${entries.map((track) => `<article><div>${radar(track.scores, { className: "mini-radar" })}</div><p>${safe(track.artist)}</p><h2>${safe(track.title)}</h2><dl><div><dt>SONG</dt><dd>${rating(track.scores.song)}</dd></div><div><dt>VOCAL</dt><dd>${rating(track.scores.vocal)}</dd></div><div><dt>OVERALL</dt><dd>${rating(track.scores.overall)}</dd></div></dl></article>`).join("")}</div></section>`;
};

export const compare = () => {
  const ratings = storage.get("how-i-hear-music:rating-sessions:v2", {}); const comparisons = Object.entries(ratings).map(([id, visitor]) => ({ track: findTrack(id), visitor })).filter(({ track, visitor }) => Number.isFinite(track?.scores?.overall) && Number.isFinite(visitor?.scores?.overall));
  const distances = comparisons.map(({ track, visitor }) => Math.abs(track.scores.overall - visitor.scores.overall)); const average = distances.length ? distances.reduce((sum, value) => sum + value, 0) / distances.length : null; const match = average === null ? null : Math.max(0, Math.round((1 - average / 11) * 100));
  const content = comparisons.length >= 3 ? `<span class="mono">TASTE MATCH / ${comparisons.length} SHARED TRACKS</span><h2>${match}% listening proximity.</h2><p>This is the average distance between your Overall scores and Andrew’s—not a compatibility verdict.</p><div class="taste-distances">${comparisons.slice(0, 6).map(({ track, visitor }) => `<span><b>${safe(track.title)}</b><em>${rating(visitor.scores.overall)} / ${rating(track.scores.overall)}</em></span>`).join("")}</div>` : `<span class="mono">TASTE MATCH / LOCAL-ONLY</span><h2>${comparisons.length ? `${3 - comparisons.length} more shared ${3 - comparisons.length === 1 ? "track" : "tracks"}.` : "Comparison begins with a real score."}</h2><p>Rate at least three archived tracks. Your ratings remain in this browser and no public profile is created.</p>`;
  return `${pageHeader("TASTE / COMPARE", "Two ways of hearing.", "Rate selected tracks in the dedicated workspace, then reveal the distance.", link("/rate", "RATE A TRACK", "button primary"))}<section class="compare-callout">${content}</section>`;
};

const boundariesMarkup = () => {
  const patterns = antiRecommendationPatterns();
  const spots = blindSpots({ albums: archiveVisibleAlbums() });
  const blind = spots.length ? `<section class="blind-spots">${spots.map((spot, index) => `<article><span class="mono">BLIND SPOT ${String(index + 1).padStart(2, "0")} · ${safe(spot.type)}</span><h2>${safe(spot.title)}</h2><p>${safe(spot.copy)}</p><dl><div><dt>${spot.type.includes("COVERAGE") ? "EVIDENCE SIGNAL" : "TRAIT AFFINITY"}</dt><dd>${Math.round(spot.affinity * 100)}</dd></div><div><dt>EXPLORED</dt><dd>${Math.round((1 - spot.coverageGap) * 100)}%</dd></div></dl>${spot.links?.length ? `<div class="blind-spot-entrypoints"><span class="mono">CURRENT EVIDENCE</span>${spot.links.map((item) => link(item.href, `${item.label} →`)).join("")}</div>` : ""}</article>`).join("")}</section>` : `<section class="analysis-empty"><span class="mono">NOT ENOUGH EVIDENCE</span><h2>A blind spot needs both stable taste evidence and a measurable coverage gap.</h2><p>Language and era require confirmed metadata for at least 60% and ten scored records; Sonic gaps require eight explicitly placed tracks.</p>${link("/taste/dna", "READ TASTE DNA →", "text-link")}</section>`;
  return `${pageHeader("TASTE / BOUNDARIES", "What probably won't work for me?", "Patterns describe recurring distance and coverage gaps, never a genre stereotype.")}${goodNotMineMarkup()}<section class="taste-boundary-patterns"><span class="mono">RECURRING BOUNDARIES</span>${patterns.length ? `<section class="anti-patterns">${patterns.map((pattern) => `<article><span class="mono">PATTERN FROM ${pattern.records.length} TRACKS</span><h2>${safe(pattern.title)}</h2><p>${safe(pattern.copy)}</p><div>${pattern.records.slice(0, 5).map((record) => link(`/archive/tracks/${record.id}`, record.title)).join("")}</div></article>`).join("")}</section>` : `<section class="analysis-empty"><span class="mono">NOT ENOUGH EVIDENCE</span><h2>No boundary repeats across three tracks yet.</h2><p>More explicit ratings may reveal a pattern; the site will not manufacture one.</p></section>`}</section><section class="taste-boundary-blind"><span class="mono">BLIND SPOTS</span>${blind}</section>`;
};

export const dna = () => {
  const traits = tasteDNA();
  return `${pageHeader("TASTE / DNA", "What repeats beneath the ratings.", "A trait needs at least five supporting tracks. Genre is not used as the primary explanation.")}${profileSummary()}<details class="dna-method"><summary>HOW STRENGTH AND CONFIDENCE WORK <span>+</span></summary><p><b>Strength</b> combines the supporting tracks' average Overall, lift above your archive baseline and score consistency. <b>Confidence</b> increases with evidence count, consistency and recency. Neither number predicts whether a new track will work.</p></details>${traits.length ? `<section class="taste-dna">${traits.map((trait, index) => `<article id="${safe(trait.id)}"><span class="mono">${String(index + 1).padStart(2, "0")}</span><div><h2>${safe(trait.label)}</h2><p>${safe(trait.copy)}</p><small class="mono">${trait.evidenceCount} TRACKS · AVG ${rating(trait.average)} VS ARCHIVE ${rating(trait.baseline)} · ${Math.round(trait.confidence * 100)}% CONFIDENCE</small><details class="dna-evidence"><summary>INSPECT EVIDENCE <span>+</span></summary><div><span class="mono">CONTRIBUTING TRACKS</span>${trait.evidence.map((record) => link(`/archive/tracks/${trackId(record)}`, `${record.title} · ${rating(record.scores?.overall)}`)).join("")}</div>${trait.limitingEvidence.length ? `<div><span class="mono">LIMITING EVIDENCE / BELOW BASELINE</span>${trait.limitingEvidence.map((record) => link(`/archive/tracks/${trackId(record)}`, `${record.title} · ${rating(record.scores?.overall)}`)).join("")}</div>` : `<p>No contributing track falls below the current archive baseline.</p>`}</details></div>${tasteTraitMark(trait)}</article>`).join("")}</section>` : `<section class="analysis-empty"><span class="mono">NOT ENOUGH EVIDENCE</span><h2>No recurring trait reaches five explicit tracks yet.</h2><p>Ratings can contribute to score-based traits. Why This Works, Listening Temperature and history make the model more specific.</p>${link("/rate", "ADD LISTENING EVIDENCE →", "text-link")}</section>`}`;
};

// Retain previous URLs as aliases while presenting one coherent analysis surface.
export const profile = () => dna();
export const goodNotMine = () => boundariesMarkup();
export const antiRecommendation = () => boundariesMarkup();
export const blindSpotPage = () => boundariesMarkup();

const sonicAxis = (key) => sonicDimensions[key] || sonicDimensions.warmCold;
export const sonicMap = () => {
  const params = new URLSearchParams(location.search); const keys = Object.keys(sonicDimensions); const xKey = keys.includes(params.get("x")) ? params.get("x") : "warmCold"; const yKey = keys.includes(params.get("y")) ? params.get("y") : "denseSparse"; const values = readSonic();
  const points = Object.entries(values).map(([id, sonic]) => ({ track: findTrack(id), sonic })).filter((item) => item.track && Number.isFinite(Number(item.sonic[xKey])) && Number.isFinite(Number(item.sonic[yKey])));
  const axisOptions = (selected) => keys.map((key) => `<option value="${key}"${key === selected ? " selected" : ""}>${sonicDimensions[key].label}</option>`).join(""); const x = sonicAxis(xKey); const y = sonicAxis(yKey);
  const chart = points.length ? `<svg class="sonic-map" viewBox="0 0 720 520" role="img" aria-label="Sonic map"><line x1="60" y1="260" x2="660" y2="260"></line><line x1="360" y1="40" x2="360" y2="480"></line><text x="60" y="500">${x.low}</text><text x="660" y="500" text-anchor="end">${x.high}</text><text x="360" y="24" text-anchor="middle">${y.low}</text><text x="360" y="516" text-anchor="middle">${y.high}</text>${points.map(({ track, sonic }, index) => `<g style="view-transition-name:sonic-point-${index}" transform="translate(${360 + Number(sonic[xKey]) * 280} ${260 + Number(sonic[yKey]) * 200})"><circle r="5"></circle><text x="10" y="4">${safe(track.title)}</text></g>`).join("")}</svg>` : `<div class="analysis-empty"><span class="mono">NO SONIC CHARACTER YET</span><h2>Save Listening Temperature on a Track detail page.</h2></div>`;
  return `${pageHeader("TASTE / SONIC MAP", "Character, not quality.", "Choose two axes. Every point comes from an explicit local descriptor.")}<form class="sonic-axis-form"><label><span class="mono">X AXIS</span><select name="x">${axisOptions(xKey)}</select></label><label><span class="mono">Y AXIS</span><select name="y">${axisOptions(yKey)}</select></label><button class="button" type="submit">REDRAW</button></form>${chart}`;
};

const groupMemberOptions = (type) => (type === "track" ? allTracks().map((track) => [trackId(track), `${track.title} — ${track.artist}`]) : allArtists().map((artist) => [artist.id, artist.name])).map(([id, label]) => `<option value="${safe(id)}">${safe(label)}</option>`).join("");
const memberName = (type, id) => type === "track" ? findTrack(id)?.title : allArtists().find((artist) => artist.id === id)?.name;
export const familyTree = () => {
  const groups = readTasteGroups();
  return `${pageHeader("TASTE / CONSTELLATION", "Musical family, without genre boxes.", "One artist or track may appear in several manually curated branches.")}<section class="taste-constellation">${groups.length ? groups.map((group) => `<article><span class="mono">${safe(group.memberType.toUpperCase())} GROUP</span><h2>${safe(group.name)}</h2>${group.description ? `<p>${safe(group.description)}</p>` : ""}<ul>${group.memberIds.map((id) => `<li>${safe(memberName(group.memberType, id) || "Missing local record")}</li>`).join("")}</ul><button type="button" data-remove-group="${safe(group.id)}">REMOVE GROUP</button></article>`).join("") : `<div class="analysis-empty"><span class="mono">NO GROUPS YET</span><h2>Build the first branch from what actually matters.</h2></div>`}</section><form class="taste-group-form"><span class="mono">CURATE A GROUP</span><label><span>NAME</span><input name="name" required maxlength="60" placeholder="Harmony-heavy"></label><label><span>DESCRIPTION</span><input name="description" maxlength="160" placeholder="What connects these records?"></label><label><span>MEMBER TYPE</span><select name="memberType"><option value="artist">ARTISTS</option><option value="track">TRACKS</option></select></label><label><span>MEMBERS</span><select name="memberIds" multiple size="8">${groupMemberOptions("artist")}</select></label><button class="button primary" type="submit">ADD GROUP</button><p data-group-status>Stored only in this browser.</p></form>`;
};

export const portrait = () => {
  const scope = new URLSearchParams(location.search).get("scope") || "9plus"; const evidence = currentEvidence(); const tracks = scope === "all" ? evidence : evidence.filter((track) => Number(track.scores?.overall) >= (scope === "favorites" ? 9.5 : 9)); const albums = storage.get("how-i-hear-music:journal:v1", []).filter((entry) => entry.type === "album" && Array.isArray(entry.tracks));
  return `${pageHeader("TASTE / LISTENING PORTRAIT", "The archive as a print.", "Track shapes and album landscapes become one sampled composition—not a dashboard.")}<nav class="portrait-filters">${[["9plus", "9+ TRACKS"], ["favorites", "FAVORITES"], ["all", "ALL TIME"]].map(([value, label]) => link(`/taste/portrait?scope=${value}`, label, value === scope ? "active" : "")).join("")}</nav>${listeningPortrait({ tracks, albums, year: "MY LISTENING PORTRAIT" })}`;
};

export const bindTaste = (path, navigate) => {
  if (path === "/taste/sonic-map") document.querySelector(".sonic-axis-form")?.addEventListener("submit", (event) => { event.preventDefault(); const values = new FormData(event.currentTarget); navigate(`/taste/sonic-map?x=${encodeURIComponent(values.get("x"))}&y=${encodeURIComponent(values.get("y"))}`); });
  if (path !== "/taste/family-tree") return;
  const form = document.querySelector(".taste-group-form"); const type = form?.elements.memberType; const members = form?.elements.memberIds;
  type?.addEventListener("change", () => { members.innerHTML = groupMemberOptions(type.value); });
  form?.addEventListener("submit", (event) => { event.preventDefault(); const values = new FormData(form); try { addTasteGroup({ name: values.get("name"), description: values.get("description"), memberType: values.get("memberType"), memberIds: values.getAll("memberIds") }); navigate(path); } catch (error) { form.querySelector("[data-group-status]").textContent = error.message; } });
  document.querySelector(".taste-constellation")?.addEventListener("click", (event) => { const button = event.target.closest("[data-remove-group]"); if (!button) return; removeTasteGroup(button.dataset.removeGroup); navigate(path); });
};
